name: Deploy to production

on:
  push:
    branches: [ master ]

jobs:

  deploy:
    name: Build image
    runs-on: ubuntu-latest

    steps:
    

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Check out code
      uses: actions/checkout@v2

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY:  public.ecr.aws/d2s0x5m0/risk_classifier
        ECR_REPOSITORY: risk_classifier
        IMAGE_TAG: ${{ github.sha }}
      run: |
        echo "$ECR_REGISTRY"
        # docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        # docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker build -t risk_classifier .
        docker tag risk_classifier:latest public.ecr.aws/d2s0x5m0/risk_classifier:latest
        docker push public.ecr.aws/d2s0x5m0/risk_classifier:latest

